server:
  port: 8083

spring:
  application:
    name: oms-inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5435/oms_inventory_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: test
      secret-key: test

sqs:
  payment-failed-queue: payment-failed-queue